nombre = input("Escriba el nombre del primer trabajador: ")
apellido = input("Escriba su apellido: ")
edad = int(input("Escriba su edad: "))
print(f"El nombre del primer trabajador es {nombre} {apellido} de {edad} años")
print("'Nombre' es:", type(nombre))
print("'Apellido' es:", type(apellido))
print("'Edad' es:", type(edad))
print("*****")
nombre2 = input("Escriba el nombre del segundo trabajador: ")
apellido2 = input("Escriba su apellido: ")
edad2 = int(input("Escriba su edad: "))
print(f"El nombre del segundo trabajador es {nombre2} {apellido2} de {edad2} años")
print("'Nombre' es:", type(nombre2))
print("'Apellido' es:", type(apellido2))
print("'Edad' es:", type(edad2))
print("*****")
lista = [nombre, edad, nombre2, edad2]
print(lista)
lista2 = lista[1] + lista[3]
print("La suma de la edad de ambos trabajadores es:", lista2)