var1 = input("Ingresa un número: ")
var2 = input("Ingresa otro número: ")
list = input("Ingresa números de una lista: ")
lista = list.split()
list2 = input("Qué número eliminar de esta lista: ")
print("Lista original:", lista)
lista.remove(list2)
list3 = (var1, var2, lista)
print("Lista actualizada:", list3)
print("Elemento eliminado:" , list2)